using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using JetBrains.Annotations;
using UnityEditor;
#if ADDRESSABLES_ENABLED
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
#endif
using UnityEditor.Compilation;
using UnityEditor.UIElements;
using UnityEngine;
using UnityEngine.UIElements;
using Button = UnityEngine.UIElements.Button;
using Object = UnityEngine.Object;

namespace BrunoMikoski.ScriptableObjectCollections
{

    [CustomEditor(typeof(ScriptableObjectCollection), true)]
    public class CollectionCustomEditor : Editor
    {
        private enum SortType
        {
            Default,
            ByName,
            ByType,
        }


        private const string WAITING_FOR_SCRIPT_TO_BE_CREATED_KEY = "WaitingForScriptTobeCreated";
        private static ScriptableObject LAST_ADDED_COLLECTION_ITEM;

        [SerializeField]
        private VisualTreeAsset visualTreeAsset;
        [SerializeField] 
        private VisualTreeAsset collectionItemVisualTreeAsset;


        [NonSerialized]
        private Type generatorType;
        [NonSerialized]
        private IScriptableObjectCollectionGeneratorBase generator;

        protected virtual bool AllowCustomTypeCreation => true;
        private bool IsAutoGenerated => generatorType != null;

        private ListView collectionItemListView;
        private ScriptableObjectCollection collection;

        private TextField currentRenamingTextField;
        private Label currentRenamingLabel;
        private TextField namespaceTextField;
        private Button expandShrinkButton;

        private List<ScriptableObject> filteredItems = new();
        
        private HelpBox helpbox;
        private Toggle writeAddressablesToggle;
        private Button generateStaticFileButton;


        private bool sortReversed;
        private SortType currentSortType = SortType.Default;

        protected virtual bool CanBeReorderable
        {
            get
            {
                // If we are supposed to protect the item order, do not allow items to be reordered by dragging.
                if (collection != null && collection.ShouldProtectItemOrder)
                    return false;

                return true;
            }
        }

        protected virtual bool DisplayAddButton
        {
            get
            {
                // If this is a generated collection and it's set to remove items that aren't re-generated, then it
                // doesn't make sense for you to add items because they will be removed next time you generate.
                if (IsAutoGenerated && generator.ShouldRemoveNonGeneratedItems)
                    return false;
                return true;
            }
        }

        protected virtual bool DisplayRemoveButton
        {
            get
            {
                // If this is a generated collection and it's set to remove items that aren't re-generated, then it
                // doesn't make sense for you to remove items because they will be added back next time you generate.
                if (IsAutoGenerated && generator.ShouldRemoveNonGeneratedItems)
                    return false;

                // If we are supposed to protect the item order, do not allow items to be removed, otherwise you could
                // remove items from the middle and change the order.
                if (collection != null && collection.ShouldProtectItemOrder)
                    return false;

                return true;
            }
        }

        private static bool IsWaitingForNewTypeBeCreated
        {
            get => SessionState.GetBool(WAITING_FOR_SCRIPT_TO_BE_CREATED_KEY, false);
            set => SessionState.SetBool(WAITING_FOR_SCRIPT_TO_BE_CREATED_KEY, value);
        }

        public static ScriptableObject AddNewItem(ScriptableObjectCollection collection, Type itemType)
        {
            ScriptableObject collectionItem = collection.AddNew(itemType);
            Selection.objects = new Object[] { collection };
            LAST_ADDED_COLLECTION_ITEM = collectionItem;
            return collectionItem;
        }

        public override VisualElement CreateInspectorGUI()
        {
            VisualElement root = new();
            visualTreeAsset.CloneTree(root);

            collection = (ScriptableObjectCollection)target;
            collection.RefreshCollection();

            collectionItemListView = root.Q<ListView>("items-list-view");

            collectionItemListView.makeItem = MakeCollectionItemListItem;
            collectionItemListView.bindItem = BindCollectionItemListItem;
            collectionItemListView.itemIndexChanged += OnCollectionItemOrderChanged;
            
            if (ScriptableObjectCollectionUtility.IsTryingToGoToItem(out int targetIndex))
            {
                collectionItemListView.schedule.Execute(() =>
                {
                    ScriptableObjectCollectionUtility.ClearGoToItem();
                    ScriptableObject targetItem = collection.Items[targetIndex];
                    int filteredItemIndex = filteredItems.IndexOf(targetItem);
                    SetAllToExpandState(false);
                    SetExpandedStateForIndex(filteredItemIndex, true);
                    collectionItemListView.ScrollToItem(filteredItemIndex);
                }).ExecuteLater(100);
            }

            collectionItemListView.reorderable = CanBeReorderable;
            collectionItemListView.RegisterCallback<KeyUpEvent>(OnKeyUpOnCollectionListView, TrickleDown.TrickleDown);

            ReloadFilteredItems(false);
            collectionItemListView.itemsSource = filteredItems;


            Button addNewItemButton = root.Q<Button>("unity-list-view__add-button");
            addNewItemButton.clickable.activators.Clear();
            addNewItemButton.RegisterCallback<MouseDownEvent>(OnClickAddNewItem);
            addNewItemButton.SetEnabled(DisplayAddButton);

            Button removeSelectedItemsButton = root.Q<Button>("unity-list-view__remove-button");
            removeSelectedItemsButton.clickable.activators.Clear();
            removeSelectedItemsButton.RegisterCallback<MouseUpEvent>(OnClickRemoveSelectedItems);
            removeSelectedItemsButton.SetEnabled(DisplayRemoveButton);

            Button synchronizeAssetsButton = root.Q<Button>("synchronize-items-button");
            synchronizeAssetsButton.clickable.activators.Clear();
            synchronizeAssetsButton.RegisterCallback<MouseUpEvent>(OnClickToSynchronizeAssets);

            generateStaticFileButton = root.Q<Button>("generate-static-file-button");
            generateStaticFileButton.clickable.activators.Clear();
            generateStaticFileButton.RegisterCallback<MouseUpEvent>(OnClickGenerateStaticFile);
            UpdateGenerateStaticFileButtonState();


            Button generateItemsButton = root.Q<Button>("generate-auto-items");
            generateItemsButton.clickable.activators.Clear();
            generateItemsButton.RegisterCallback<MouseUpEvent>(OnClickGenerateItems);
            generateItemsButton.style.display = generatorType != null ? DisplayStyle.Flex : DisplayStyle.None;

            Toggle automaticLoadToggle = root.Q<Toggle>("automatic-loaded-toggle");
            automaticLoadToggle.RegisterValueChangedCallback(evt =>
            {
                UpdateAutomaticallyLoaded();
                UpdateHelpBox();
            });
            
            Toggle writeAsPartialClass = root.Q<Toggle>("write-partial-class-toggle");
            writeAsPartialClass.value = SOCSettings.Instance.GetWriteAsPartialClass(collection);
            writeAsPartialClass.SetEnabled(CodeGenerationUtility.CheckIfCanBePartial(collection));
            writeAsPartialClass.RegisterValueChangedCallback(evt =>
            {
                SOCSettings.Instance.SetWriteAsPartialClass(collection, evt.newValue);
            });

            
            ObjectField generatedScriptsParentFolderObjectField =
                root.Q<ObjectField>("generated-scripts-parent-folder");
            generatedScriptsParentFolderObjectField.value = SOCSettings.Instance.GetParentDefaultAssetScriptsFolderForCollection(collection);
            
            generatedScriptsParentFolderObjectField.RegisterValueChangedCallback(evt =>
            {
                SOCSettings.Instance.SetGeneratedScriptsParentFolder(collection, evt.newValue);
                writeAsPartialClass.SetEnabled(CodeGenerationUtility.CheckIfCanBePartial(collection));
                UpdateGenerateStaticFileButtonState();
            });


            Toggle useBaseClassForItems = root.Q<Toggle>("base-class-for-items-toggle");
            useBaseClassForItems.value = SOCSettings.Instance.GetUseBaseClassForItem(collection);
            useBaseClassForItems.RegisterValueChangedCallback(evt =>
            {
                SOCSettings.Instance.SetUsingBaseClassForItems(collection, evt.newValue);
            });

            TextField staticFileNameTextField = root.Q<TextField>("static-filename-textfield");
            staticFileNameTextField.value = SOCSettings.Instance.GetStaticFilenameForCollection(collection);
            staticFileNameTextField.RegisterValueChangedCallback(evt =>
            {
                SOCSettings.Instance.SetStaticFilenameForCollection(collection, evt.newValue);
            });

            Toggle enforceIndirectAccessToggle = root.Q<Toggle>("enforce-indirect-access");
            enforceIndirectAccessToggle.value = SOCSettings.Instance.GetEnforceIndirectAccess(collection);
            enforceIndirectAccessToggle.RegisterValueChangedCallback(evt =>
            {
                SOCSettings.Instance.SetEnforceIndirectAccess(collection, evt.newValue);
                UpdateHelpBox();
            });
            

            namespaceTextField = root.Q<TextField>("namespace-textfield");
            namespaceTextField.value = SOCSettings.Instance.GetNamespaceForCollection(collection);
            namespaceTextField.RegisterValueChangedCallback(OnNamespaceTextFieldChanged);

            VisualElement extraProperties = root.Q<VisualElement>("extra-properties-visual-element");
            IMGUIContainer imguiContainer = extraProperties.Q<IMGUIContainer>();
            InspectorElement.FillDefaultInspector(imguiContainer, serializedObject, this);
            

            VisualElement advancedOptionsVisualElement = root.Q<VisualElement>("advanced-options-visual-element");
            helpbox = new HelpBox
            {
                style =
                {
                    display = DisplayStyle.None
                }
            };

            advancedOptionsVisualElement.Add(helpbox);

            writeAddressablesToggle = root.Q<Toggle>("write-addressables-load-toggle");
            writeAddressablesToggle.SetValueWithoutNotify(SOCSettings.Instance.GetWriteAddressableLoadingMethods(collection));
            writeAddressablesToggle.style.display = DisplayStyle.None;
            writeAddressablesToggle.RegisterValueChangedCallback(evt =>
            {
                SOCSettings.Instance.SetWriteAddressableLoadingMethods(collection, evt.newValue);
                UpdateHelpBox();
            });
            
            
            expandShrinkButton = root.Q<Button>("expand-button");
            
            expandShrinkButton.clickable.activators.Clear();
            expandShrinkButton.RegisterCallback<MouseUpEvent>(OnToggleExpand);


            Button sortButton = root.Q<Button>("sort-button");
            sortButton.clickable.activators.Clear();

            sortButton.RegisterCallback<MouseUpEvent>(OnPressOnSortButton);



            ToolbarSearchField toolbarSearchField = root.Q<ToolbarSearchField>();
            toolbarSearchField.RegisterValueChangedCallback(OnSearchInputChanged);

            
            root.schedule.Execute(OnVisualTreeCreated).ExecuteLater(100);

            return root;
        }

        private void OnPressOnSortButton(MouseUpEvent evt)
        {
            if (evt.button == 0)
            {
                sortReversed = !sortReversed;
                ReloadFilteredItems();
            }
            else
            {
                GenericMenu sortingOptions = new GenericMenu();
                sortingOptions.AddItem(new GUIContent("Default"), currentSortType == SortType.Default, () =>
                {
                    currentSortType = SortType.Default;
                    ReloadFilteredItems();
                });

                sortingOptions.AddItem(new GUIContent("Name"), currentSortType == SortType.ByName, () =>
                {
                    currentSortType = SortType.ByName;
                    ReloadFilteredItems();
                });

                sortingOptions.AddItem(new GUIContent("Type"), currentSortType == SortType.ByType, () =>
                {
                    currentSortType = SortType.ByType;
                    ReloadFilteredItems();
                });

                sortingOptions.AddSeparator("");


                sortingOptions.AddItem(new GUIContent("Apply Current Sorting"), false, () =>
                {
                    collection.Items.Clear();
                    for (int i = 0; i < filteredItems.Count; i++)
                    {
                        ScriptableObject filteredItem = filteredItems[i];
                        collection.Add(filteredItem);
                    }
                    EditorUtility.SetDirty(collection);
                });


                sortingOptions.ShowAsContext();
            }
        }

        private void UpdateAutomaticallyLoaded()
        {
            CollectionsRegistry.Instance.UpdateAutoSearchForCollections();
        }

        private VisualElement MakeCollectionItemListItem()
        {
            TemplateContainer makeCollectionItemListItem = collectionItemVisualTreeAsset.CloneTree();
            return makeCollectionItemListItem;
        }

        private void BindCollectionItemListItem(VisualElement targetElement, int targetIndex)
        {
            ScriptableObject targetItem = filteredItems[targetIndex];
            if (targetItem == null)
            {
                return;
            }

            IMGUIContainer imguiContainer = targetElement.Q<IMGUIContainer>("imgui-container");
            Foldout foldout = targetElement.Q<Foldout>("header-foldout");
            foldout.viewDataKey = targetIndex.ToString();
            foldout.text = targetItem.name;
            
            Editor editor = EditorCache.GetOrCreateEditorForObject(targetItem);

            Label titleLabel = foldout.Q<Label>();
            titleLabel.RegisterCallback<MouseDownEvent, int>(RenameItemAtIndex, targetIndex, TrickleDown.TrickleDown);

            targetElement.parent.parent.RegisterCallback<MouseUpEvent, int>(ShowOptionsForIndex, targetIndex);

            imguiContainer.onGUIHandler = () =>
            {
                {
                    editor.OnInspectorGUI();
                }
            };
        }

        private void OnKeyUpOnCollectionListView(KeyUpEvent evt)
        {
            if (currentRenamingLabel != null)
                return;

            switch (evt.keyCode)
            {
                case KeyCode.F2:
                {
                    int selectedIndex = collectionItemListView.selectedIndex;
                    if (selectedIndex >= 0)
                    {
                        RenameItemAtIndex(selectedIndex);
                    }

                    break;
                }
                case KeyCode.RightArrow:
                {
                    if (evt.modifiers.HasFlag(EventModifiers.Alt))
                    {
                        SetAllToExpandState(true);
                    }
                    else
                    {
                        SetExpandedStateForIndex(collectionItemListView.selectedIndex, true);
                    }

                    break;
                }
                case KeyCode.LeftArrow:
                {
                    if (evt.modifiers.HasFlag(EventModifiers.Alt))
                    {
                        SetAllToExpandState(false);
                    }
                    else
                    {
                        SetExpandedStateForIndex(collectionItemListView.selectedIndex, false);
                    }

                    break;
                }
            }
        }

        private void OnCollectionItemOrderChanged(int fromIndex, int toIndex)
        {
            ScriptableObject sourceItem = filteredItems[fromIndex];
            ScriptableObject targetItem = filteredItems[toIndex];

            int sourceIndex = collection.Items.IndexOf(sourceItem);
            int targetIndex = collection.Items.IndexOf(targetItem);

            Undo.RecordObject(collection, "Reorder Item");
            collection.Items.RemoveAt(sourceIndex);
            collection.Items.Insert(targetIndex, sourceItem);
            EditorUtility.SetDirty(collection);

            ReloadFilteredItems();
        }

        private void OnToggleExpand(MouseUpEvent evt)
        {
            bool? isOn = null;
            for (int i = 0; i < filteredItems.Count; i++)
            {
                VisualElement item = collectionItemListView.GetRootElementForIndex(i);

                Foldout foldout = item.Q<Foldout>();
                if (!isOn.HasValue)
                {
                    isOn = foldout.value;
                }

                foldout.value = !isOn.Value;
            }

            if (!isOn.HasValue)
            {
                isOn = false;
            }

            expandShrinkButton.text = isOn.Value ? "▸◂" : "◂▸";
        }

        private void OnEnable()
        {
            collection = (ScriptableObjectCollection)target;

            if (!CollectionsRegistry.Instance.IsKnowCollection(collection))
                CollectionsRegistry.Instance.ReloadCollections();

            // Need to cache this before the reorderable list is created, because it affects how the list is displayed.
            generatorType = CollectionGenerators.GetGeneratorTypeForCollection(collection.GetType());
            generator = generatorType == null ? null : CollectionGenerators.GetGenerator(generatorType);
        }

        private void OnDisable()
        {
            SOCSettings.Instance.SaveCollectionSettings(collection, true);
        }

        private void OnNamespaceTextFieldChanged(ChangeEvent<string> evt)
        {
            string validCharsOnly = Regex.Replace(evt.newValue, @"[^A-Za-z0-9_\.]+", "_");
            string noLeadingNumbers = Regex.Replace(validCharsOnly, @"(?<=^|\.)(\d)", "_$1");
            string singleUnderscores = Regex.Replace(noLeadingNumbers, @"_+", "_");
            string trimmed = singleUnderscores.Trim('_');
            trimmed = trimmed.TrimEnd('.');
            namespaceTextField.SetValueWithoutNotify(trimmed);

            SOCSettings.Instance.SetNamespaceForCollection(collection, trimmed);
        }

        private void OnClickToSynchronizeAssets(MouseUpEvent evt)
        {
            collection.RefreshCollection();
            ReloadFilteredItems();
        }

        private void OnClickGenerateItems(MouseUpEvent evt)
        {
            CollectionGenerators.RunGenerator(generatorType, collection);
        }

        private void OnClickGenerateStaticFile(MouseUpEvent evt)
        {
            CodeGenerationUtility.GenerateStaticCollectionScript(collection);
        }

        private void OnClickRemoveSelectedItems(MouseUpEvent evt)
        {


            if (!collectionItemListView.selectedIndices.Any())
            {
                if (!EditorUtility.DisplayDialog($"Delete Item",
                        $"Are you sure you want to delete {filteredItems[^1].name}?", "Yes", "No"))
                {
                    return;
                }

                DeleteItemAtIndex(filteredItems.Count - 1);
            }
            else
            {
                if (!EditorUtility.DisplayDialog($"Delete {collectionItemListView.selectedIndices.Count()} Items",
                        $"Are you sure you want to delete all {collectionItemListView.selectedIndices.Count()} items?", "Yes", "No"))
                {
                    return;
                }

                List<ScriptableObject> itemsToBeDuplicated = new List<ScriptableObject>();
                foreach (int selectedIndex in collectionItemListView.selectedIndices)
                {
                    itemsToBeDuplicated.Add(filteredItems[selectedIndex]);
                }

                foreach (ScriptableObject item in itemsToBeDuplicated)
                {
                    DeleteItemAtIndex(collection.IndexOf(item));
                }
            }

            ReloadFilteredItems();
        }

        private void OnVisualTreeCreated()
        {
            UpdateHelpBox();
            UpdateGenerateStaticFileButtonState();
            UpdateWriteAddressablesMethodsState();

            if (LAST_ADDED_COLLECTION_ITEM != null)
            {
                int targetIndex = collection.IndexOf(LAST_ADDED_COLLECTION_ITEM);
                RenameItemAtIndex(targetIndex);
                LAST_ADDED_COLLECTION_ITEM = null;
            }
        }

        private void UpdateWriteAddressablesMethodsState()
        {
            writeAddressablesToggle.style.display = IsAddressableAsset(collection) && !collection.AutomaticallyLoaded ? DisplayStyle.Flex : DisplayStyle.None;
        }

        private void UpdateGenerateStaticFileButtonState()
        {
            generateStaticFileButton.SetEnabled(
                AssetDatabase.IsValidFolder(SOCSettings.Instance.GetParentFolderPathForCollection(collection)));
        }

        private void OnClickAddNewItem(MouseDownEvent evt)
        {
            List<Type> itemsSubclasses = new() { collection.GetItemType() };
            TypeCache.TypeCollection sub = TypeCache.GetTypesDerivedFrom(collection.GetItemType());
            for (int i = 0; i < sub.Count; i++)
            {
                itemsSubclasses.Add(sub[i]);
            }

            GenericMenu optionsMenu = new GenericMenu();

            for (int i = 0; i < itemsSubclasses.Count; i++)
            {
                Type itemSubClass = itemsSubclasses[i];
                if (itemSubClass.IsAbstract)
                    continue;

                optionsMenu.AddItem(new GUIContent(itemSubClass.Name), false,
                    () => { AddNewItemOfType(itemSubClass); });
            }

            optionsMenu.AddSeparator("");

            if (AllowCustomTypeCreation)
            {
                for (int i = 0; i < itemsSubclasses.Count; i++)
                {
                    Type itemSubClass = itemsSubclasses[i];

                    if (itemSubClass.IsSealed)
                        continue;

                    optionsMenu.AddItem(new GUIContent($"Create New/class $NEW : {itemSubClass.Name}"), false,
                        () => { CreateAndAddNewItemOfType(itemSubClass); });
                }
            }

            optionsMenu.ShowAsContext();
        }

        private void OnSearchInputChanged(ChangeEvent<string> evt)
        {
            OnSearchValueChanged(evt.newValue);
        }

        private void OnSearchValueChanged(string targetText)
        {
            if (string.IsNullOrEmpty(targetText))
            {
                ReloadFilteredItems();
                return;
            }

            filteredItems.Clear();

            for (int i = 0; i < collection.Count; i++)
            {
                ScriptableObject collectionItem = collection[i];
                if (collectionItem.name.IndexOf(targetText, StringComparison.OrdinalIgnoreCase) > -1)
                {
                    filteredItems.Add(collectionItem);
                }
            }

            collectionItemListView.RefreshItems();
        }
        
        
        private void UpdateHelpBox()
        {
            bool isAddressableAsset = IsAddressableAsset(collection);

            HelpBoxMessageType helpBoxMessageType = HelpBoxMessageType.Warning;

            StringBuilder finalMessage = new StringBuilder();
            
            if (isAddressableAsset && !collection.AutomaticallyLoaded && !SOCSettings.Instance.GetWriteAddressableLoadingMethods(collection))
            {
                finalMessage.AppendLine("You can use the Write Addressable Loading Methods to generate the loading methods for this collection.");
                helpBoxMessageType = HelpBoxMessageType.Info;
            }

            if (isAddressableAsset && collection.AutomaticallyLoaded)
            {
                finalMessage.AppendLine(
                    "This collection is set to be automatically loaded but it's also an Addressables asset, Maybe this should be set to be load manually ");
                
                helpBoxMessageType = HelpBoxMessageType.Warning;
            }

            if (isAddressableAsset && !collection.AutomaticallyLoaded && !SOCSettings.Instance.GetEnforceIndirectAccess(collection))
            {
                finalMessage.AppendLine("This collection is an not automatically loaded Addressables asset, you should consider enforcing indirect access to avoid loading all the items at once.");
                
                helpBoxMessageType = HelpBoxMessageType.Warning;
            }

            if (finalMessage.Length > 0)
            {
                helpbox.style.display = DisplayStyle.Flex;
                helpbox.messageType = helpBoxMessageType;
                helpbox.text = finalMessage.ToString();
            }
            else
            {
                helpbox.style.display = DisplayStyle.None;
            }
        }

        private bool IsAddressableAsset(ScriptableObject target)
        {
#if ADDRESSABLES_ENABLED
            string assetPath = AssetDatabase.GetAssetPath(target);
            AddressableAssetSettings settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
                return false;
            
            AddressableAssetEntry entry = settings.FindAssetEntry(AssetDatabase.AssetPathToGUID(assetPath));
            return entry != null;
#else
            return false;
#endif
        }

        private ScriptableObject AddNewItemOfType(Type targetType, bool autoFocusForRename = true)
        {
            Undo.IncrementCurrentGroup();
            ScriptableObject newItem = collection.AddNew(targetType);
            Undo.RegisterCreatedObjectUndo(newItem, "Create New Item");
            Undo.RecordObject(collection, "Add New Item");
            Undo.SetCurrentGroupName($"Created new item {newItem.name}");
            ReloadFilteredItems();

            if (autoFocusForRename)
            {
                int newItemIndex = filteredItems.IndexOf(newItem);
                collectionItemListView.ScrollToItem(newItemIndex);
                RenameItemAtIndex(newItemIndex);
            }

            return newItem;
        }

        private void SetAllToExpandState(bool targetState)
        {
            for (int i = 0; i < filteredItems.Count; i++)
            {
                SetExpandedStateForIndex(i, targetState);
            }
        }

        private void SetExpandedStateForIndex(int index, bool state)
        {
            VisualElement item = collectionItemListView.GetRootElementForIndex(index);
            if (item == null)
                return;

            Foldout foldout = item.Q<Foldout>();
            foldout.value = state;
        }


        private void CreateAndAddNewItemOfType(Type itemSubClass)
        {
            CreateNewCollectionItemFromBaseWizard.Show(itemSubClass, success =>
            {
                if (success)
                {
                    IsWaitingForNewTypeBeCreated = true;
                }
            });
        }

        protected void DeleteItemAtIndex(int selectedIndex)
        {
            ScriptableObject scriptableObject = filteredItems[selectedIndex];
            if (scriptableObject == null)
            {
                ReloadFilteredItems();
                return;
            }

            Undo.RecordObject(collection, "Remove Item");

            filteredItems.Remove(scriptableObject);
            collection.Remove(scriptableObject);

            AssetDatabase.DeleteAsset(AssetDatabase.GetAssetPath(scriptableObject));

            AssetDatabase.SaveAssetIfDirty(collection);
        }

        private void ReloadFilteredItems(bool refreshListView = true)
        {
            filteredItems.Clear();

            for (int i = 0; i < collection.Items.Count; i++)
            {
                ScriptableObject scriptableObject = collection.Items[i];
                if (scriptableObject == null)
                    continue;

                filteredItems.Add(scriptableObject);
            }

            switch (currentSortType)
            {
                case SortType.Default:
                    break;
                case SortType.ByName:
                    filteredItems = filteredItems.OrderBy(item => item.name).ToList();
                    break;
                case SortType.ByType:
                    filteredItems = filteredItems.OrderBy(item => item.GetType().Name).ToList();
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }

            if (sortReversed)
            {
                filteredItems.Reverse();
            }

            if (refreshListView)
            {
                collectionItemListView.RefreshItems();
            }
        }

        private void ShowOptionsForIndex(MouseUpEvent evt, int targetIndex)
        {
            if (evt.button != 1)
                return;

            int selectedItemsCount = collectionItemListView.selectedIndices.Count();
            bool singleItemSelected = selectedItemsCount == 1;

            ScriptableObject scriptableObject = filteredItems[targetIndex];

            GenericMenu menu = new GenericMenu();

            if (singleItemSelected)
            {
                menu.AddItem(
                    new GUIContent("Copy Values"),
                    false,
                    () => { CopyCollectionItemUtility.SetSource(scriptableObject); }
                );
            }
            else
            {
                menu.AddDisabledItem(
                    new GUIContent("Copy Values"),
                    false);
            }
            if (CopyCollectionItemUtility.CanPasteToTarget(scriptableObject))
            {
                menu.AddItem(
                    new GUIContent("Paste Values"),
                    false,
                    () =>
                    {
                        if (selectedItemsCount > 0)
                        {
                            foreach (int selectedIndex in collectionItemListView.selectedIndices)
                            {
                                CopyCollectionItemUtility.ApplySourceToTarget(filteredItems[selectedIndex]);
                            }
                        }
                        else
                        {
                            CopyCollectionItemUtility.ApplySourceToTarget(scriptableObject);
                        }
                    }
                );
            }
            else
            {
                menu.AddDisabledItem(new GUIContent("Paste Values"));
            }

            menu.AddSeparator("");

            menu.AddItem(
                new GUIContent("Duplicate Item"),
                false,
                () =>
                {
                    if (selectedItemsCount > 0)
                    {
                        List<ScriptableObject> itemsToBeDuplicated = new List<ScriptableObject>();
                        foreach (int selectedIndex in collectionItemListView.selectedIndices)
                        {
                            itemsToBeDuplicated.Add(filteredItems[selectedIndex]);
                        }

                        foreach (ScriptableObject item in itemsToBeDuplicated)
                        {
                            DuplicateItem(item, false);
                        }
                    }
                    else
                    {
                        DuplicateItem(targetIndex);
                    }
                }
            );

            menu.AddItem(
                new GUIContent("Delete Item"),
                false,
                () =>
                {
                    if (selectedItemsCount > 0)
                    {
                        if (!EditorUtility.DisplayDialog($"Delete {collectionItemListView.selectedIndices.Count()} Items",
                                $"Are you sure you want to delete all {collectionItemListView.selectedIndices.Count()} items?", "Yes", "No"))
                        {
                            return;
                        }

                        List<ScriptableObject> itemsToBeDuplicated = new List<ScriptableObject>();
                        foreach (int selectedIndex in collectionItemListView.selectedIndices)
                        {
                            itemsToBeDuplicated.Add(filteredItems[selectedIndex]);
                        }

                        foreach (ScriptableObject item in itemsToBeDuplicated)
                        {
                            DeleteItemAtIndex(collection.IndexOf(item));
                        }
                    }
                    else
                    {
                        if (!EditorUtility.DisplayDialog($"Delete Item",
                                $"Are you sure you want to delete {filteredItems[^1].name}?", "Yes", "No"))
                        {
                            return;
                        }

                        DeleteItemAtIndex(targetIndex);
                    }
                }
            );

            menu.AddSeparator("");
            menu.AddItem(
                new GUIContent("Select Asset"),
                false,
                () =>
                {
                    if (selectedItemsCount > 0)
                    {
                        SelectItemAtIndex(collectionItemListView.selectedIndices.ToArray());
                    }
                    else
                    {
                        SelectItemAtIndex(targetIndex);
                    }
                }
            );

            menu.ShowAsContext();
        }

        private void SelectItemAtIndex(params int[] index)
        {
            Object[] selectedObjects = new Object[index.Length];
            for (int i = 0; i < index.Length; i++)
            {
                selectedObjects[i] = filteredItems[index[i]];
            }
            Selection.objects = selectedObjects;
        }

        private void DuplicateItem(int index, bool showRenameAfter = true)
        {
            ScriptableObject source = filteredItems[index];
            DuplicateItem(source, showRenameAfter);
        }

        private void DuplicateItem(ScriptableObject source, bool showRenameAfter)
        {
            CopyCollectionItemUtility.SetSource(source);
            ScriptableObject newItem = AddNewItemOfType(source.GetType(), false);
            CopyCollectionItemUtility.ApplySourceToTarget(newItem);

            if (showRenameAfter)
            {
                int targetIndex = filteredItems.IndexOf(newItem);
                RenameItemAtIndex(targetIndex);
            }
            else
            {
                AssetDatabaseUtils.RenameAsset(newItem, $"{source.name} (Copy)");
                AssetDatabase.SaveAssetIfDirty(newItem);
                ReloadFilteredItems();
            }
        }

        private void RenameItemAtIndex(MouseDownEvent evt, int targetIndex)
        {
            RenameItemAtIndex(targetIndex);
        }
        
        private void RenameItemAtIndex(int targetIndex)
        {
            ClearCurrentRenamingItem();

            Undo.RecordObject(filteredItems[targetIndex], "Rename Item");
            VisualElement targetElement = collectionItemListView.GetRootElementForIndex(targetIndex);

            currentRenamingLabel = targetElement.Q<Label>("", "unity-toggle__text");

            currentRenamingLabel.style.display = DisplayStyle.None;

            currentRenamingTextField = targetElement.Q<TextField>();
            currentRenamingTextField.RegisterCallback<FocusOutEvent>(OnRenamingAssetLostFocus);
            currentRenamingTextField.RegisterValueChangedCallback(_ => OnFinishRenamingItem(targetIndex));

            currentRenamingTextField.SetValueWithoutNotify(currentRenamingLabel.text);
            currentRenamingTextField.style.display = DisplayStyle.Flex;
            currentRenamingTextField.SelectAll();
            currentRenamingTextField.Focus();
            collectionItemListView.ClearSelection();
        }

        private void OnRenamingAssetLostFocus(FocusOutEvent evt)
        {
            ClearCurrentRenamingItem();
        }

        private void OnFinishRenamingItem(int targetIndex)
        {
            if (currentRenamingTextField == null)
                return;

            string targetNewName = currentRenamingTextField.text;
            if (targetNewName.IsReservedKeyword())
            {
                Debug.LogError($"{targetNewName} is a reserved C# keyword, will cause issues with " +
                               $"code generation, reverting to previous name");
            }
            else
            {
                ScriptableObject asset = filteredItems[targetIndex];
                Undo.RecordObject(asset, "Rename Item");
                AssetDatabaseUtils.RenameAsset(asset, targetNewName);
                AssetDatabase.SaveAssetIfDirty(asset);
            }

            ClearCurrentRenamingItem();
        }

        private void ClearCurrentRenamingItem()
        {
            if (currentRenamingTextField == null)
                return;

            currentRenamingTextField.style.display = DisplayStyle.None;
            currentRenamingLabel.style.display = DisplayStyle.Flex;
            currentRenamingLabel.text = currentRenamingTextField.text;
            currentRenamingTextField.SetValueWithoutNotify("");
            currentRenamingLabel = null;
            currentRenamingTextField = null;
        }

        class CollectionCustomEditorAssetPostProcessor : AssetPostprocessor
        {
            [UsedImplicitly]
            private static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets,
                string[] movedAssets, string[] movedFromAssetPaths, bool didDomainReload)
            {
                if (!didDomainReload)
                    return;

                if (!IsWaitingForNewTypeBeCreated)
                    return;

                IsWaitingForNewTypeBeCreated = false;

                string lastGeneratedCollectionScriptPath =
                    CreateNewCollectionItemFromBaseWizard.LastGeneratedCollectionScriptPath.Value;
                string lastCollectionFullName = CreateNewCollectionItemFromBaseWizard.LastCollectionFullName.Value;

                if (string.IsNullOrEmpty(lastGeneratedCollectionScriptPath))
                    return;

                CreateNewCollectionItemFromBaseWizard.LastCollectionFullName.Value = string.Empty;
                CreateNewCollectionItemFromBaseWizard.LastGeneratedCollectionScriptPath.Value = string.Empty;

                string assemblyName =
                    CompilationPipeline.GetAssemblyNameFromScriptPath(lastGeneratedCollectionScriptPath);

                Type targetType = Type.GetType($"{lastCollectionFullName}, {assemblyName}");

                if (CollectionsRegistry.Instance.TryGetCollectionFromItemType(targetType,
                        out ScriptableObjectCollection collection))
                {
                    Selection.activeObject = null;
                    LAST_ADDED_COLLECTION_ITEM = collection.AddNew(targetType);
                    Selection.activeObject = collection;
                }
            }
        }
    }
}